name: Python Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Clona el repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # Configura la versión de Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Instala dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecuta pruebas con pytest
      - name: Ejecutar pruebas con pytest
        run: |
          pytest